[server]
port=81
cookieSecret = "E2853F133466832CE75A2441D9D14"

[theme]
base="dark"
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"