password = "12345"
latitude_sgt = "0.516755"
longitude_sgt = "117.535089"
log_url = 'http://localhost:8080/ewacspro/api/logs/loader-hauler'
auth_url = 'http://localhost:5107/api/user/login-api'

[db_credentials]
server = "kpcsgt-db04"
username = "test_ryan"
password = "samarinda123"
port = "1433"
database1 = "TEST_DEV"